"""Initial trading data models with api manager structure

Revision ID: fc1b7806bebd
Revises: 
Create Date: 2025-08-06 10:19:09.882708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1b7806bebd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executed_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ibkr_order_id', sa.Integer(), nullable=False),
    sa.Column('ibkr_contract_id', sa.Integer(), nullable=True),
    sa.Column('ibkr_parent_order_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_purpose', sa.String(length=15), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('aux_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('last_fill_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('fill_time', sa.DateTime(), nullable=False),
    sa.Column('last_update_time', sa.DateTime(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executed_trades_bot_name'), 'executed_trades', ['bot_name'], unique=False)
    op.create_index(op.f('ix_executed_trades_ibkr_order_id'), 'executed_trades', ['ibkr_order_id'], unique=False)
    op.create_index(op.f('ix_executed_trades_ibkr_parent_order_id'), 'executed_trades', ['ibkr_parent_order_id'], unique=False)
    op.create_index(op.f('ix_executed_trades_symbol'), 'executed_trades', ['symbol'], unique=False)
    op.create_table('order_cancellations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ibkr_order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('cancelled_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_cancellations_bot_name'), 'order_cancellations', ['bot_name'], unique=False)
    op.create_index(op.f('ix_order_cancellations_ibkr_order_id'), 'order_cancellations', ['ibkr_order_id'], unique=False)
    op.create_index(op.f('ix_order_cancellations_symbol'), 'order_cancellations', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_bot_name'), 'orders', ['bot_name'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_table('trade_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('max_concurrent_trades', sa.Integer(), nullable=False),
    sa.Column('current_active_trades', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_bot_name'), 'trade_signals', ['bot_name'], unique=False)
    op.create_index(op.f('ix_trade_signals_strategy_name'), 'trade_signals', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_trade_signals_symbol'), 'trade_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_signals_timestamp'), 'trade_signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_signals_timestamp'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_symbol'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_strategy_name'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_bot_name'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_bot_name'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_cancellations_symbol'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_ibkr_order_id'), table_name='order_cancellations')
    op.drop_index(op.f('ix_order_cancellations_bot_name'), table_name='order_cancellations')
    op.drop_table('order_cancellations')
    op.drop_index(op.f('ix_executed_trades_symbol'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_ibkr_parent_order_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_ibkr_order_id'), table_name='executed_trades')
    op.drop_index(op.f('ix_executed_trades_bot_name'), table_name='executed_trades')
    op.drop_table('executed_trades')
    # ### end Alembic commands ###
